train:
  max_epoch: 200
  save_epoch: 20
  shot: 1
  query: 15
  train_way: 30
  test_way: 5
  save_path: 'exps/exp-v1/proto'
  gpu: '1'
  pretrain: "/space1/songkun/project/prototypeNet/save/proto-1/max-acc.pth"
  topk: 500
  progalambda: 0.25
test:
  gpu: 0'
  load: 'exps/exp-v1/proto/max-acc.pth'
  result: 'exps/exp-v1/proto/result'
  batch: 20000
  way: 5
  shot: 1
  query: 30
  topk: 500
  progalambda: 0.25